# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Mod Properties
maven_group=work.lclpnet.mods.gaco
mod_id=game-map-utils
mod_version=0.4.4

minecraft_compat=1.21.11

# Dependencies
fabric_version=0.139.5+1.21.11
kibu_version=0.153.2+1.21.11
kibu_world_api_version=0.9.2+1.21.11
gaco_version=0.14.3+1.21.11
fantasy_version=0.7.0+1.21.11