[versions]
minecraft = "26.1.2"
fabric-api = "0.147.0+26.1.2"
fabric-loader = "0.19.2"
fabric-loom = "1.16-SNAPSHOT"
gradle-build-tools = "1.7.0"
java = "25"
fantasy = "0.8.0-beta.1+26.1.1"
kotlin = "2.3.21"
fabric-kotlin = "1.13.11+kotlin.2.3.21"

[plugins]
fabric-loom = { id = "net.fabricmc.fabric-loom", version.ref = "fabric-loom" }
maven-publish = { id = "maven-publish" }
gradle-build-utils = { id = "gradle-build-utils", version.ref = "gradle-build-tools" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
java = { id = "java" }

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-language-kotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabric-kotlin" }
fantasy = { module = "xyz.nucleoid:fantasy", version.ref = "fantasy" }
